import { Icon } from '@joinprisma/components';
import clsx from 'clsx';
import type { NextPage } from 'next';
import Head from 'next/head';
import FeedbackCarousel from '../components/FeedbackCarousel';
import Heading from '../components/Heading';
import Hero from '../components/hero/Hero';
import LinksCarousel from '../components/LinksCarousel';
import Paragraph from '../components/Paragraph';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="overflow-x-clip">
        <Hero />
        <main className="px-2 md:px-6 pt-20 sm:pt-40 mx-auto max-w-[1392px]">
          <Heading
            text="A live learning experience - delightful for kids, powerful for teachers"
            color="yellow"
          />
          <Paragraph text="Prisma LIVE is the custom live learning platform for the Prisma online school. It has been conceived as a strategic bet to differentiate Prisma’s online school offering and make it highly scalable while maintaining teacher quality and learner delight." />
          <FeedbackCarousel />

          {/* Videos */}
          <ul className="mb-20 space-y-40">
            {[
              {
                heading: 'Making live teaching a breeze',
                body: 'Prisma LIVE brings together all the content and faciliation tools in one place, freeing up teachers to focus on what matters most: connecting with kids and providing a great learning experience.',
                videoTitle: 'Overview',
                videoTitleClass:
                  'bg-yellow left-[51px] bottom-[58px] rotate-[-0.81deg]',
                videoBackground: '#FFD38B',
              },
              {
                heading:
                  'An immersive learning experience, not a stale video conference',
                body: 'Prisma LIVE turns static lessons into interactive, dynamic experiences that alternate seamlessly and naturally between layouts and interactive elements.',
                videoTitle: (
                  <div>
                    Learner <br /> experience
                  </div>
                ),
                videoTitleClass:
                  'bg-green rotate-[2deg] left-[50px] bottom-[48px]',
                videoBackground: '#81E088',
              },
              {
                heading: 'Breakout rooms that aren’t awkward',
                body: 'We’ve designed our breakout rooms so educators can observe what’s going on without disturbing learners. No more cycling through rooms trying to understand what’s going on. At the same time, learners have all instructions and materials right at their fingertips inside each room.',
                videoTitle: (
                  <div>
                    Breakout <br /> rooms
                  </div>
                ),
                videoTitleClass:
                  'bg-purple left-[51px] bottom-[61px] rotate-[-0.81deg]',
                videoBackground: '#E2AEFF',
              },
              {
                heading: 'A collaborative editor for curriculum designers',
                body: 'The editor is where live learning experiences are designed. We’ve made it performant and collaborative',
                videoTitle: 'Editor',
                videoTitleClass:
                  'bg-blue rotate-[2deg] left-[50px] bottom-[48px]',
                videoBackground: '#BCD4FF',
              },
            ].map((videoData) => (
              <li
                className="flex flex-col-reverse items-center lg:flex-row lg:gap-20 lg:odd:flex-row-reverse"
                key={videoData.heading}
              >
                <div className="pt-8 space-y-6 sm:px-10 lg:px-5 xl:px-10">
                  <h3 className="text-display text-on-surface">
                    {videoData.heading}
                  </h3>
                  <p className="text-outline text-headline">{videoData.body}</p>
                </div>
                <div
                  className="rounded-4 aspect-video w-full sm:w-4/5 lg:w-[580px] xl:w-[690px] relative flex-shrink-0"
                  style={{ backgroundColor: videoData.videoBackground }}
                >
                  <div
                    className={clsx(
                      'absolute text-on-secondary shadow-md text-display-lg px-2 py-1.5 rounded-2',
                      videoData.videoTitleClass
                    )}
                    style={{
                      textShadow:
                        '0px 22.1px 27.6px rgba(0, 0, 0, 0.1), 0px 8.8px 11px rgba(0, 0, 0, 0.1)',
                    }}
                  >
                    {videoData.videoTitle}
                  </div>
                </div>
              </li>
            ))}
          </ul>

          <LinksCarousel />

          {/* learn more section */}
          <div
            className="mb-40 rounded-[48px] w-full py-24 px-10"
            style={{
              background:
                'radial-gradient(38.22% 131.68% at 7.33% 108.42%, rgba(56, 231, 255, 0.5888) 0%, rgba(255, 225, 94, 0.64) 100%) /* warning: gradient uses a rotation that is not supported by CSS and may not behave as expected */, radial-gradient(32.61% 112.38% at 100% 17.08%, #FF8E5E 0%, #FFEFB7 100%)',
            }}
          >
            <h2 className="mb-6 text-center text-on-surface text-display-lg">
              Want to learn more?
            </h2>
            <p className="mx-auto mb-12 text-center text-on-surface text-headline">
              Sugar plum caramels powder sweet roll carrot cake biscuit.
            </p>
            <button className="mx-auto flex h-16 w-[280px] items-center justify-center gap-3 bg-tertiary hover:bg-tertiary-hover active:bg-tertiary-active text-tertiary-container rounded-4 shadow text-label">
              <Icon name="lightning" className="w-6 h-6" />
              <span>Learn more</span>
            </button>
          </div>

          <Heading text="The people who built it 🚀" color="purple" />
          <Paragraph text="Prisma LIVE was built by a team spanning half the globe, from the Czech Republic to Uruguay. Together, we often made the impossible happen and always had fun while doing it." />

          <ul className="grid grid-cols-1 mb-40 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-y-6 place-items-center">
            {[
              {
                imageUrl: '',
                color: '#F5B981',
                name: 'Andrés',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#FFB4A9',
                name: 'Andrea',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#FFE15E',
                name: 'Alain',
                title: 'Founder & Co-President',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#6DDF77',
                name: 'Juan',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#FFE15E',
                name: 'Dominique',
                title: 'Product Lead',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#FFD480',
                name: 'Javi',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#85CEFF',
                name: 'Diego',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#6FD8D6',
                name: 'Fede',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#85CEFF',
                name: 'Fabián',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#F5B981',
                name: 'Dominik',
                title: 'Product Designer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#B38FFF',
                name: 'Martín',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
              {
                imageUrl: '',
                color: '#DB9CFC',
                name: 'Leti',
                title: 'Software Engineer',
                social: {
                  linkedin: '',
                  twitter: '',
                },
              },
            ].map((person) => (
              <li className="w-full space-y-6 h-fit sm:even:translate-y-1/2 md:even:translate-y-0 lg:even:translate-y-20">
                <img
                  src={person.imageUrl}
                  className="mx-auto w-[271px] max-w-[90%] aspect-square rounded-[72px] shadow"
                  style={{ background: person.color }}
                />
                <div className="space-y-2">
                  <h3 className="text-center text-display-sm text-on-surface">
                    {person.name}
                  </h3>
                  <p className="text-center text-body text-outline">
                    {person.title}
                  </p>
                  <div className="flex justify-center gap-2">
                    <a
                      href={person.social.linkedin}
                      className="relative flex items-center justify-center flex-shrink-0 w-12 h-12 overflow-hidden transition-colors border rounded-full border-outline/15 group hover:text-surface"
                      target="_blank"
                    >
                      <div
                        className="absolute inset-0 transition-opacity opacity-0 group-hover:opacity-100 -z-1"
                        style={{ background: person.color }}
                      />
                      <svg
                        width="25"
                        height="24"
                        viewBox="0 0 25 24"
                        fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg"
                        className="z-10"
                        aria-label={`${person.name}'s LinkedIn profile`}
                      >
                        <path d="M6.69604 4.02895C6.69604 5.14974 5.76077 6.0579 4.60644 6.0579C3.45211 6.0579 2.51685 5.14974 2.51685 4.02895C2.51685 2.90897 3.45211 2 4.60644 2C5.76077 2 6.69604 2.90897 6.69604 4.02895ZM6.71289 7.68105H2.5V20.6663H6.71289V7.68105ZM13.4383 7.68105H9.25242V20.6663H13.4392V13.8499C13.4392 10.0598 18.5191 9.74977 18.5191 13.8499V20.6663H22.7218V12.4442C22.7218 6.04897 15.2044 6.28189 13.4383 9.43001V7.68105Z" />
                      </svg>
                    </a>
                    <a
                      href={person.social.twitter}
                      className="relative flex items-center justify-center flex-shrink-0 w-12 h-12 overflow-hidden transition-colors border rounded-full border-outline/15 group hover:text-surface"
                      target="_blank"
                    >
                      <div
                        className="absolute inset-0 transition-opacity opacity-0 group-hover:opacity-80 -z-1"
                        style={{ background: person.color }}
                      />
                      <svg
                        width="25"
                        height="24"
                        viewBox="0 0 25 24"
                        fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg"
                        className="z-10"
                        aria-label={`${person.name}'s Twitter profile`}
                      >
                        <path d="M8.85937 21.1108C16.4903 21.1108 20.6641 14.5272 20.6641 8.81802C20.6641 8.63103 20.6641 8.44488 20.6519 8.25957C21.4639 7.64797 22.1648 6.8907 22.7219 6.02322C21.9646 6.37261 21.1614 6.60175 20.3389 6.70297C21.205 6.16303 21.8532 5.3138 22.1629 4.31332C21.3485 4.81656 20.4575 5.17123 19.5284 5.362C18.2424 3.93797 16.1989 3.58944 14.5438 4.51183C12.8887 5.43423 12.0336 7.39815 12.458 9.30236C9.12217 9.12821 6.01414 7.48744 3.90744 4.78838C2.80626 6.76247 3.36872 9.28792 5.19193 10.5557C4.53168 10.5353 3.88583 10.3499 3.30887 10.015C3.30887 10.0326 3.30887 10.0512 3.30887 10.0697C3.30942 12.1263 4.70156 13.8976 6.63739 14.3049C6.02659 14.4783 5.38572 14.5037 4.76404 14.379C5.30756 16.139 6.86515 17.3446 8.64016 17.3793C7.17103 18.5817 5.35618 19.2344 3.48763 19.2324C3.15753 19.2318 2.82776 19.211 2.5 19.1701C4.39732 20.438 6.60497 21.1106 8.85937 21.1074" />
                      </svg>
                    </a>
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </main>

        <footer className="border-t border-outline/15 px-2 md:px-6 mx-auto max-w-[1392px]">
          <div className="py-10 tracking-wide text-outline text-body-sm">
            © 2022 Prisma. All rights reserved.
          </div>
        </footer>
      </div>
    </>
  );
};

export default Home;
